version: 3.0.0.{build}
os: Visual Studio 2017
configuration: Release

before_build:
  - cmd: dotnet --info
  - cmd: dotnet restore

test_script:
  - cmd: dotnet test tests/StatsdClient.Tests/

after_test:
  - cmd: dotnet pack -c Release src/StatsdClient/ /p:Version={version}

artifacts:
  - name: NuGet package
    path: 'src\StatsdClient\bin\Release\*.nupkg'
